server:
  port: 13000
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: localhost
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/