server:
  port: 24000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost     # spring session使用
  session:
    store-type: redis   # spring session使用
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/
short:
  message:
    app-code: 61f2eaa3c43e42ad82c26fbbe1061311
    host: https://feginesms.market.alicloudapi.com
    method: GET
    path: /codeNotice
    sign: 151003
    skin: 84683
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN